"use server";

import { createServerClient } from "@/lib/supabase/server";
import { createOrderSchema, type CreateOrderInput } from "@/lib/validations/order";
import type { Order } from "@/types";

interface CreateOrderSuccess {
  success: true;
  order: Order;
}

interface CreateOrderError {
  success: false;
  error: string;
}

type CreateOrderResult = CreateOrderSuccess | CreateOrderError;

/**
 * Creates a new service order with audit logging and optional scheduling.
 * Multi-step insert: order → audit log(s) → schedule.
 */
export async function createOrder(
  input: CreateOrderInput,
  userId: string
): Promise<CreateOrderResult> {
  // Re-validate on the server (never trust client data)
  const parsed = createOrderSchema.safeParse(input);
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0].message };
  }

  const data = parsed.data;
  const supabase = await createServerClient();

  const hasTechnician = data.technicianId !== undefined && data.technicianId !== "";
  const hasSchedule = data.scheduledAt !== undefined && data.scheduledAt !== "";
  const status = hasTechnician ? "assigned" : "new";

  // Step 1: Insert into orders (order_no auto-generated by trigger)
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      customer_name: data.customerName,
      customer_phone: data.customerPhone,
      address: data.address,
      problem_description: data.problemDescription,
      service_type_id: data.serviceTypeId,
      quoted_price: data.quotedPrice,
      assigned_technician_id: hasTechnician ? data.technicianId : null,
      admin_notes: data.adminNotes || null,
      status,
      scheduled_at: hasSchedule ? data.scheduledAt : null,
    })
    .select()
    .single();

  if (orderError) {
    console.error("Failed to create order:", orderError.message);
    return { success: false, error: "Failed to create order. Please try again." };
  }

  // Step 2: Audit log — order created
  const { error: auditError } = await supabase.from("audit_logs").insert({
    order_id: order.id,
    action: "created",
    old_value: null,
    new_value: status,
    performed_by: userId,
  });

  if (auditError) {
    console.error("Failed to create audit log:", auditError.message);
  }

  // Step 3: Audit log — technician assigned (if applicable)
  if (hasTechnician) {
    const { error: assignError } = await supabase.from("audit_logs").insert({
      order_id: order.id,
      action: "assigned",
      old_value: "new",
      new_value: "assigned",
      performed_by: userId,
    });

    if (assignError) {
      console.error("Failed to create assignment audit log:", assignError.message);
    }
  }

  // Step 4: Schedule entry (if scheduled_at provided)
  if (hasSchedule) {
    const { error: scheduleError } = await supabase
      .from("order_schedules")
      .insert({
        order_id: order.id,
        scheduled_at: data.scheduledAt,
        rescheduled_from: null,
        reason: null,
        created_by: userId,
      });

    if (scheduleError) {
      console.error("Failed to create schedule entry:", scheduleError.message);
    }
  }

  return { success: true, order };
}
